// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUWonMM5ZcmGVi2y53jNKOSduWcMJJ9Zg',
    appId: '1:30633795984:web:2bae2e8d94dce839075315',
    messagingSenderId: '30633795984',
    projectId: 'chamados-1df0d',
    authDomain: 'chamados-1df0d.firebaseapp.com',
    storageBucket: 'chamados-1df0d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXbiB0V-Xo_lZbX1DfMx6_COT9SHG2hbw',
    appId: '1:30633795984:android:58b74951e67a8061075315',
    messagingSenderId: '30633795984',
    projectId: 'chamados-1df0d',
    storageBucket: 'chamados-1df0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgbTXkzvE-QCFWGcJOZdY9kRpAMiOGgUs',
    appId: '1:30633795984:ios:2be5294dd8b325e4075315',
    messagingSenderId: '30633795984',
    projectId: 'chamados-1df0d',
    storageBucket: 'chamados-1df0d.appspot.com',
    iosClientId: '30633795984-3b6l5peseqqb3f90u3qfrrvqpae9ih79.apps.googleusercontent.com',
    iosBundleId: 'com.example.chamados',
  );
}
